spring:
  application:
    name: SoundSpace
  jackson:
    data-format: yyyy-MM-dd HH:mm
  profiles:
    active:
      - dbDev
      - cors
      - oauth
      - jwt
server:
  port: 9000
  servlet:
    context-path: /api


springdoc:
  swagger-ui:
    path: /
    csrf:
      enabled: true
