jwt:
  access-token:
    secret: whereUAccesswhereUAccess-whereUAccesswhereURegister
    expiration: 3600
  refresh-token:
    secret: whereURefreshwhereURefreshwhereURefresh-whereURegister
    expiration: 864000
